name: Update Events JSON

on:
  schedule:
    # 0:00 UTC is 9:00 JST
    - cron: '0 0 * * 6'
  workflow_dispatch:


jobs:
  update-events:
    runs-on: ubuntu-latest
    container:
      image: dwdraju/alpine-curl-jq
    permissions:
      contents: write
      pull-requests: write
    env:
      CONNPASS_API_KEY: ${{ secrets.CONNPASS_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run update script and validate
        run: |
          chmod +x scripts/update-events.sh
          ./scripts/update-events.sh
          jq . src/routes/Event/events.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: 'chore: update events [auto]'
          body: 'Automated update of events.json.'
          branch: 'chore-update-events-''
          branch-suffix: timestamp
          base: main
          add-paths: 'src/routes/Event/events.json'
          commit-message: 'chore: update events.json'
