name: Update Events JSON

on:
  schedule:
    # 0:00 UTC is 9:00 JST, run daily
    - cron: '0 0 * * *'
  workflow_dispatch:


jobs:
  update-events:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      CONNPASS_API_KEY: ${{ secrets.CONNPASS_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          branch: main

      - name: Run update script and validate
        run: |
          chmod +x scripts/update-events.sh
          docker run -v $PWD:/target -e "CONNPASS_API_KEY=$CONNPASS_API_KEY" dwdraju/alpine-curl-jq bash /target/scripts/update-events.sh
          jq . src/routes/Event/events.json

      - name: Commit and push events file changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Update events.json" src/routes/Event/events.json || echo "No changes to commit"
          git push
